@startuml
allowmixing

Package "Game model" {
    class World {
        GAME_LENGTH_SECONDS
        currentTime
        generateTerrainFeatures()
        addMapObject()
        updateWorldState()
        process()
        handleEvent()
        closeBuilding()
        modifyEfficiency()
        addActiveEvent()
        saveScore()
    }
    class MapObjectHolder {
        add()
        remove()
        getByUse()
        getByType()
        getByFeature()
        getByGrid()
        spaceIsOccupied()
    }
    abstract class MapObject {
        placed
        screenPosition
        gridCoords
        width
        height
        bounds
        spriteName
        snapToGrid()
        clone()
    }
    class TerrainObject {
        feature
    }
    class BuildingObject {
        built
        unbuiltSpriteName
        uses
        resetConstruction()
    }
    class GymBuilding
    class HallsBuilding
    class LectureHallBuilding
    class Pub
    class PiazzaBuilding
    class EventManager {
        processEvents(deltaTime)
        disableEvent()
        enableEvent()
    }

    class AchievementManager {

    }

    class Satisfaction {
        BUILDING_DISTANCES_SCORE_CAP
        COMPLETION_SCORE_CAP
        EVENTS_SCORE_CAP
        BUILDING_VALUES_SCORE_CAP
        updateScore()
        updateAverageDistances()
    }
    class GridUtils {
        GRID_WIDTH
        GRID_HEIGHT
        getGridSquareScreenCoords()
        getGridCoords()
    }
}

Package "Interface" {
    class ScreenManager {
        process()
    }
    class GameScreen {
        VIEWPORT_WIDTH
        VIEWPORT_HEIGHT
        draw()
        input()
        logic()
        setUpSideMenu()
        drawGrid()
        drawActiveEvents()
    }
    class MenuScreen {
        draw()
        input()
        logic()
    }
    class LeaderboardScreen {
        draw()
        input()
        logic()
    }
}

ScreenManager -- GameScreen
ScreenManager -- MenuScreen
ScreenManager -- LeaderboardScreen

GameScreen -- World

World -- GridUtils
World -- EventManager
World -- AchievementManager
World -- MapObjectHolder
World -- Satisfaction

MapObjectHolder -- MapObject
MapObjectHolder -- BuildingObject
MapObjectHolder -- TerrainObject

MapObject -- BuildingObject
MapObject -- TerrainObject

BuildingObject -- GymBuilding
BuildingObject -- HallsBuilding
BuildingObject -- LectureHallBuilding
BuildingObject -- Pub
BuildingObject -- PiazzaBuilding

@enduml
