@startuml
'https://plantuml.com/sequence-diagram
participant EventManger
actor User

EventManger -> User : Event begins
activate User
User -> EventSatisfaction : User reacts correctly
EventSatisfaction -> User : Satisfaction increases
User -> EventSatisfaction : User reacts incorrectly
EventSatisfaction -> User : Satisfaction decreases or is unchanged
EventManger -> User : Event ends
deactivate User
User -> EventSatisfaction : User makes a change
note right : No effect

@enduml
